### PR TITLE
Sync ath11k-bdencoder + ath10k-bdencoder + PY3 support

### PR DESCRIPTION
**Pull request by ecsv**
The ath11k-bdencoder was basically a copy of 6c34812fc71785c321fb20767360bfc9ff465948:tools/scripts/ath10k/ath10k-bdencoder send through

    sed -e 's/ath11k/ath10k/g' -e 's/ATH11K/ATH10K/g'

So add the missing changes from ath10k-bdencoder after 6c34812fc71785c321fb20767360bfc9ff465948 to ath11k-bdencoder.

---

The py3 stuff is the version from PR #6 (so it should include the fix for the conflict during the merge which was forced-pushed away by @kvalo ).

### CODE REVIEW

**Comment by kvalo** [comment]
Has this been tested? I am very reluctant to take any untested code.

**Comment by ecsv** [comment]
The ath10k-bdencoder at the end is the same one as the one from #3 + the python /usr/bin/env change and the instruction comment. And afaik, I've tested all commands at that time with valid inputs

The ath11k-bdencoder is just the ath10k-bdencoder with ath10k replaced with ath11k (and some copyright changes).

**Comment by ecsv** [comment]
Btw. the ath11k ATH11K_BD_IE_BOARD_EXT equlvalency with ath10k's ATH10K_BD_IE_BOARD_EXT. The ath11k code only defines ATH11K_BD_IE_BOARD_EXT but never uses it at the moment.

**Comment by kvalo** [comment]
ath10k-bdencoder and ath11k-bdencoder are very similar on purpose. This makes it possible to change the ath11k script without worrying about breaking ath10k.

**Comment by kvalo** [comment]
While investigating the changes I also noticed that ATH11K_BD_IE_BOARD_EXT in ath11k is not used and it should be removed from ath11k. The idea here is that the board file format between ath10k and ath11k will be separate, which gives more flexibility.

**Comment by ecsv** [comment]
@kvalo just posted a py3 compatible version

**Pull request closed without merging**
